### ISSUE TITLE
c++調用trt模型的問題

### ISSUE THREAD

**Issue by MikeEnvi** [Linaom1214/TensorRT-For-YOLO-Series#59]
你好，我是先按照您的這個工程代碼中的export.py將yolov7-tiny.onnx轉換成了yolov7-tiny.trt模型。然后我在//cpp/norm/build目录下编译出了yolo可執行文件，我只是運行了以下的命令：
cd norm && mkdir build && build
cmake ..
make
./yolo ./yolov7-tiny.trt  -i  ./test.jpg

我沒有修改c++代碼的任何地方，然後出現以下錯誤：

engine init finished
[09/27/2022-10:10:02] [W] [TRT] Using an engine plan file across different models of devices is not recommended and is likely to affect performance or even cause errors.
blob image
[09/27/2022-10:10:02] [E] [TRT] 3: Cannot find binding of given name: image_arrays
[09/27/2022-10:10:02] [E] [TRT] 2: [engine.cpp::findUserRegion::1280] Error Code 2: Internal Error (Assertion index >= 0 failed. )
[09/27/2022-10:10:02] [E] [TRT] 3: Cannot find binding of given name: outputs
[09/27/2022-10:10:02] [E] [TRT] 2: [engine.cpp::findUserRegion::1280] Error Code 2: Internal Error (Assertion index >= 0 failed. )
[09/27/2022-10:10:02] [W] [TRT] The getMaxBatchSize() function should not be used with an engine built from a network created with NetworkDefinitionCreationFlag::kEXPLICIT_BATCH flag. This function will always return 1.
Cuda failure: 1
已放弃 (核心已转储)

你提示要在代碼中修改這幾行代碼：
Edit code for your model

static const int INPUT_W = 640;
static const int INPUT_H = 640;
const char* INPUT_BLOB_NAME = "image_arrays";
const char* OUTPUT_BLOB_NAME = "outputs";

你在yolo.h中的YOLO类中已经有了，我不需要再添加了吧

请问我现在该如何解决上述的错误，谢谢

**Comment by Linaom1214** [comment]
const char* INPUT_BLOB_NAME = "image_arrays";修改这一行代码为 const char* INPUT_BLOB_NAME = "images";需要和onnx模型的输入对齐---- 回复的原邮件 ***@***.***>发送日期2022年09月27日 10:27 ***@***.***> ***@***.***>主题[Linaom1214/TensorRT-For-YOLO-Series] c++調用trt模型的問題 (Issue #59)

你好，我是先按照您的這個工程代碼中的export.py將yolov7-tiny.onnx轉換成了yolov7-tiny.trt模型。然后我在//cpp/norm/build目录下编译出了yolo可執行文件，我只是運行了以下的命令：

cd norm && mkdir build && build

cmake ..

make

./yolo ./yolov7-tiny.trt  -i  ./test.jpg

我沒有修改c++代碼的任何地方，然後出現以下錯誤：

engine init finished

[09/27/2022-10:10:02] [W] [TRT] Using an engine plan file across different models of devices is not recommended and is likely to affect performance or even cause errors.

blob image

[09/27/2022-10:10:02] [E] [TRT] 3: Cannot find binding of given name: image_arrays

[09/27/2022-10:10:02] [E] [TRT] 2: [engine.cpp::findUserRegion::1280] Error Code 2: Internal Error (Assertion index >= 0 failed. )

[09/27/2022-10:10:02] [E] [TRT] 3: Cannot find binding of given name: outputs

[09/27/2022-10:10:02] [E] [TRT] 2: [engine.cpp::findUserRegion::1280] Error Code 2: Internal Error (Assertion index >= 0 failed. )

[09/27/2022-10:10:02] [W] [TRT] The getMaxBatchSize() function should not be used with an engine built from a network created with NetworkDefinitionCreationFlag::kEXPLICIT_BATCH flag. This function will always return 1.

Cuda failure: 1

已放弃 (核心已转储)

你提示要在代碼中修改這幾行代碼：

Edit code for your model

static const int INPUT_W = 640;

static const int INPUT_H = 640;

const char* INPUT_BLOB_NAME = "image_arrays";

const char* OUTPUT_BLOB_NAME = "outputs";

你在yolo.h中的YOLO类中已经有了，我不需要再添加了吧

请问我现在该如何解决上述的错误，谢谢



—Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you are subscribed to this thread.Message ID: ***@***.***>

[

{

***@***.***": "http://schema.org",

***@***.***": "EmailMessage",

"potentialAction": {

***@***.***": "ViewAction",

"target": "https://github.com/Linaom1214/TensorRT-For-YOLO-Series/issues/59",

"url": "https://github.com/Linaom1214/TensorRT-For-YOLO-Series/issues/59",

"name": "View Issue"

},

"description": "View this Issue on GitHub",

"publisher": {

***@***.***": "Organization",

"name": "GitHub",

"url": "https://github.com"

}

}

]

**Comment by MikeEnvi** [comment]
后来按照你给的方法,问题解决了,thank you very much

**Comment by MikeEnvi** [comment]
@Linaom1214  我这边今天还遇到下面一个问题:
        我基于yolov7训练了一个的用来检测人体头部(head)和手部(hand)的检测模型head_hand_detector,我也是用你这个工程代码中的export 将该模型转换成了tensorRT可以调用的模型 head_hand_detector.trt.   我用trt.py 调用head_hand_detector.trt跑出的检测结果是对的,但是我用cpp/norm下的运行时跑出的结果时错误的, 除了检测出头部和手部外,还出现很多检测框.

我发现当我用trt.py调用该模型时,如该不将trt.py文件的中self.n_classes 的值改成2的话,也会有现在C++调用时出现的错误.
class Predictor(BaseEngine):
    def __init__(self, engine_path , imgsz=(640,640)):
        super(Predictor, self).__init__(engine_path)
        self.imgsz = imgsz # your model infer image size
        self.n_classes = 2  # your model classes


在用C++调用时,我没有在yolo.hpp文件中发现表示模型检测类别数的参数可以修改,只是修改了yolo.hpp中的
static const char* class_names[] = {"head","hand"};

我用同样的C++代码调用只检测1类目标物体的yolov7模型时,结果也是正确,只是调用检测多类目标物体的模型时会出现上述问题.

弄了很久都没有解决,希望大佬指点迷津!  谢谢

**Comment by Linaom1214** [comment]
> @Linaom1214 我这边今天还遇到下面一个问题: 我基于yolov7训练了一个的用来检测人体头部(head)和手部(hand)的检测模型head_hand_detector,我也是用你这个工程代码中的export 将该模型转换成了tensorRT可以调用的模型 head_hand_detector.trt. 我用trt.py 调用head_hand_detector.trt跑出的检测结果是对的,但是我用cpp/norm下的运行时跑出的结果时错误的, 除了检测出头部和手部外,还出现很多检测框.
> 
> 我发现当我用trt.py调用该模型时,如该不将trt.py文件的中self.n_classes 的值改成2的话,也会有现在C++调用时出现的错误. class Predictor(BaseEngine): def **init**(self, engine_path , imgsz=(640,640)): super(Predictor, self).**init**(engine_path) self.imgsz = imgsz # your model infer image size self.n_classes = 2 # your model classes
> 
> 在用C++调用时,我没有在yolo.hpp文件中发现表示模型检测类别数的参数可以修改,只是修改了yolo.hpp中的 static const char* class_names[] = {"head","hand"};
> 
> 我用同样的C++代码调用只检测1类目标物体的yolov7模型时,结果也是正确,只是调用检测多类目标物体的模型时会出现上述问题.
> 
> 弄了很久都没有解决,希望大佬指点迷津! 谢谢

end2end  不需要修改类别信息， 多类目标是没问题的呀， 本身就是基于COCO数据集测试代码的。 

 C++ 如果是 不包含nms插件的模型可以通过设定
https://github.com/Linaom1214/TensorRT-For-YOLO-Series/blob/91333dc55cf580efe766be4c6aab2ab7b22421d6/cpp/norm/yolo.hpp#L125
实现类别数修改

**Comment by MikeEnvi** [comment]
@Linaom1214 我把const int num_class 的值改成2以后就正确了.谢谢
